/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package COMP3111_Lab1;

public class Library {
    
	public static void main(String agr[]) {
		System.out.println("Hello, World!");
	}
	
	public boolean someLibraryMethod() {
        return true;
    }
}
